import { createFileRoute } from "@tanstack/react-router";
import { Facebook, Instagram } from "lucide-react";
import { PageHero, SectionHeading, SocialLink } from "@/components/site-layout";
import portraitAsset from "@/assets/sonia-portrait.jpg.asset.json";
import sunsetAsset from "@/assets/sunset-detail.jpg.asset.json";

export const Route = createFileRoute("/about-the-author")({ head: () => ({ meta: [
  { title: "About Sonia I. Guzman Rosario — Author" }, { name: "description", content: "Meet Sonia I. Guzman Rosario, author of the literary novel Bethsabe of New York." }, { property: "og:title", content: "About Sonia I. Guzman Rosario" }, { property: "og:description", content: "The author behind Bethsabe of New York, a novel grounded in resilience and humanity." }, { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: AboutAuthor });

function AboutAuthor() { return <><PageHero title="About the Author" eyebrow="Sonia I. Guzman Rosario" image={sunsetAsset.url} />
  <section className="bg-muted px-5 py-24 text-primary-dark sm:px-8 lg:py-32"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[5fr_7fr] lg:items-center"><img src={portraitAsset.url} alt="Portrait of author Sonia I. Guzman Rosario" loading="lazy" className="mx-auto aspect-[4/5] w-full max-w-md border border-primary/50 object-cover object-top editorial-shadow"/><div><SectionHeading eyebrow="Novelist" title="Sonia I. Guzman Rosario" /><div className="space-y-6 text-lg leading-8"><p>Sonia I. Guzman Rosario is the author of <em>Bethsabe of New York</em>, a novel first published in Spanish as <em>Betsabé de Nueva York</em> and later presented to English-language readers.</p><p>Her work brings an intimate story of love, family, faith, and forgiveness into the defining historical setting of New York during the first year of the COVID-19 crisis.</p><p>Through Bethsabe’s journey, Guzman Rosario explores the courage of young people, the strength found in family bonds, and the enduring goodness of the human spirit.</p></div><div className="mt-8 flex gap-3"><SocialLink label="Facebook"><Facebook /></SocialLink><SocialLink label="Instagram"><Instagram /></SocialLink></div></div></div></section>
  <section className="bg-background px-5 py-24 text-center sm:px-8 lg:py-28"><blockquote className="mx-auto max-w-4xl font-display text-3xl italic leading-relaxed text-primary sm:text-4xl">“A tribute to life, hope, and resilience—and a genuine call to humanity’s civic conscience.”</blockquote></section>
  <section className="bg-muted px-5 py-24 text-primary-dark sm:px-8 lg:py-32"><div className="mx-auto max-w-3xl"><SectionHeading eyebrow="Behind the pages" title="Inspiration behind the novel" /><p className="text-lg leading-8">The novel is rooted in the extraordinary human realities of the pandemic: essential work, private grief, family devotion, and the hope that survives uncertainty. Its blend of fiction and real events preserves that moment while keeping one young woman’s emotional journey at its center.</p></div></section></>; }