/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutTheAuthorRouteImport } from './routes/about-the-author'
import { Route as AboutTheBookRouteImport } from './routes/about-the-book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTheAuthorRoute = AboutTheAuthorRouteImport.update({
  id: '/about-the-author',
  path: '/about-the-author',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTheBookRoute = AboutTheBookRouteImport.update({
  id: '/about-the-book',
  path: '/about-the-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-the-author': typeof AboutTheAuthorRoute
  '/about-the-book': typeof AboutTheBookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-the-author': typeof AboutTheAuthorRoute
  '/about-the-book': typeof AboutTheBookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-the-author': typeof AboutTheAuthorRoute
  '/about-the-book': typeof AboutTheBookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about-the-author' | '/about-the-book' | '/contact' | '/gallery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-the-author' | '/about-the-book' | '/contact' | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/about-the-author'
    | '/about-the-book'
    | '/contact'
    | '/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutTheAuthorRoute: typeof AboutTheAuthorRoute
  AboutTheBookRoute: typeof AboutTheBookRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-the-author': {
      id: '/about-the-author'
      path: '/about-the-author'
      fullPath: '/about-the-author'
      preLoaderRoute: typeof AboutTheAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-the-book': {
      id: '/about-the-book'
      path: '/about-the-book'
      fullPath: '/about-the-book'
      preLoaderRoute: typeof AboutTheBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutTheAuthorRoute: AboutTheAuthorRoute,
  AboutTheBookRoute: AboutTheBookRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
